module.exports = {
    color: {
        color: "#74147a",
        error: "#ed244f",
        vote: "0x37de85",
    },
    emojis: {
        ok: ":white_check_mark:",
        error: ":x:",
        loading: "",
        now: ":thumbsup:",
        finished: ":wave:",
        stuck: ":woozy_face:",
        stop: ":stop_button:",
        skip: ":track_next:",
        repeat_track: ":repeat_one:",
        repeat_queue: ":repeat:",
        cleared: ":boom:",
        forward: ":arrow_right:",
        rewind: ":arrow_left:",
        skipto: ":arrow_upper_left:",
        nowplaying: ":play_pause:",
        npTime: ":timer:",
        npLength: ":level_slider:",
        npProgress: ":woman_with_probing_cane:",
        autoplay: ":infinity:",
        doing: ":hourglass_flowing_sand:",
        pause: ":pause_button:",
        resume: ":play_pause:",
        remove: ":scissors:",
        seek: ":cinema:",
        perTrack: ":small_blue_diamond:",
        queueList: ":clipboard:",
        npQueue: ":microphone2:",
        infoQueue: ":information_source:",
        alreadyShuffled: ":face_with_raised_eyebrow:",
        shuffled: ":postal_horn:",
        cooldown: ":hourglass:",
        helpCmds: ":orange_book:",
     },
};
